### ISSUE TITLE
Trying to get property of non-object on $users = $object->favoritedBy()

### ISSUE THREAD

**Issue by ghost** [ChristianKuri/laravel-favorite#12]
## Detailed description
It worked on last version, but since I upgraded Laravel to 5.8 I have this error when I try to get a collection of users that have "favorited" an item.

## Context
My Favoriteable model is links (user can favourite any link of the application). 
My (very simple) Links model:
```
class Links extends Model
{
	use Favoriteable;
}
```
My Users model:
```
class User extends Authenticatable
{
    use Favoriteability;
    [...]
}
```
In a test controller, I want to
```
$link = Links::findOrFail(22);
$users = $link->favoritedBy();
```
Yes link 22 does exist in database :) The error is on `$link->favoritedBy();` then on
```
    public function favoritedBy()
    {
        return $this->favorites()->with('user')->get()->mapWithKeys(function ($item) {
            return [$item['user']->id => $item['user']];
        });
    }
```
The following are working correctly:
```
$link = Links::findOrFail($id);
$favoriteCount = $link->favoritesCount;
```
Will generate `select count(*) as aggregate from [favorites] where [favorites].[favoriteable_id] = 22 and [favorites].[favoriteable_id] is not null and [favorites].[favoriteable_type] = 'App\Models\Users\Links'` as expected
```
$link = Links::findOrFail($request->input('link_id'));
$link->toggleFavorite();
```
Will generate `select top 1 1 [exists] from [favorites] where [favorites].[favoriteable_id] = 22 and [favorites].[favoriteable_id] is not null and [favorites].[favoriteable_type] = 'App\Models\Users\Links' and [user_id] = 84` and `insert into [favorites] ([user_id], [favoriteable_id], [favoriteable_type], [updated_at], [created_at]) values (84, 22, 'App\Models\Users\Links', '2019-03-19 16:41:19.984', '2019-03-19 16:41:19.984')` as expected (same for removing)

## Possible implementation

-

## Your environment

* Laravel 5.8
* PHP 7.1.26-1+0\~20190113101856.12+jessie\~1.gbp7077bb
* Package:
```
name     : christiankuri/laravel-favorite
descrip. : Allows Laravel Eloquent models to implement a 'favorite' or 'remember' or 'follow' feature.
keywords : ChristianKuri, Follow, favoritable, favorite, favourite, laravel, laravel-favorite, package, remember
versions : * v1.3.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/ChristianKuri/laravel-favorite.git a6e519934711c4261ed546426e288432aed26422
dist     : [zip] https://api.github.com/repos/ChristianKuri/laravel-favorite/zipball/a6e519934711c4261ed546426e288432aed26422 a6e519934711c4261ed546426e288432aed26422
names    : christiankuri/laravel-favorite
```
* Linux distrib:
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
```

**Comment by ghost** [comment]
OK I think I found the problem ; for any reason, we decided to have in our Users table the primary key `id_user` not `id`. I fixed the issue by modifying: 
```
Traits\Favoriteable
public function favoritedBy()
{
	return $this->favorites()->with('user')->get()->mapWithKeys(function ($item) {
            return [$item['user']->id_user => $item['user']];
        });
}
```
```
Models\Favorite
public function user()
{
        return $this->belongsTo(Config::get('auth.providers.users.model'), 'user_id');
}
```
So it won't work correctly if we change the default primary key for the Users Model, despite the declaration of `protected $primaryKey = 'id_user';` into Users model

**Comment by ChristianKuri** [comment]
Ok, im glad everything is fixed now, ill check it out and see if I can implement something to take the declared primary key instead of the id directly
