### ISSUE TITLE
Column id

### ISSUE THREAD

**Issue by Ishodnikov** [ChristianKuri/laravel-favorite#13]
Why is column ID missing in migration?

**Comment by ChristianKuri** [comment]
There is no need for it, but if you want you can publish the migration and add it.

`php artisan vendor:publish --provider="ChristianKuri\LaravelFavorite\FavoriteServiceProvider"`

**Comment by amanpatel** [comment]
This is still relevant... I just installed the package and got this error when I tried to add a favorite:
```
 (SQL: insert into "favorites" ("user_id", "favoriteable_id", "favoriteable_type", "updated_at", "created_at") values (?, 2, App\Network, 2021-02-12 23:14:49, 2021-02-12 23:14:49) returning "id")'[49m
```
