### ISSUE TITLE
Eager load user's favourite models

### ISSUE THREAD

**Issue by romansidorov** [ChristianKuri/laravel-favorite#15]
Hi there!

I get user's favourite models: `$user->favorite(Material::class);`
But it produces many similar db-queries: https://take.ms/fuKu3

How could I eager load that?

Thanks!

**Comment by ChristianKuri** [comment]
Have to tried this? 

Something like $user->load('favorites.material')
Or you could also add $with = ['favorites.material']; to your user model

if it doesnt work use materials or something like that, im not sure how you named the relationship

**Comment by romansidorov** [comment]
> Have to tried this?
> 
> Something like $user->load('favorites.material')
> Or you could also add $with = ['favorites.material']; to your user model
> 
> if it doesnt work use materials or something like that, im not sure how you named the relationship

Yes, I tried but had no effect and caught `Call to undefined relationship [material] on model [ChristianKuri\LaravelFavorite\Models\Favorite].` error. Why should it work? Where this relationship (`favorites.material`) been declared?

**Comment by tpaksu** [comment]
@romansidorov, I found an easy way to do that:

Create a _favorite materials relationship_ method in your **User** class:

```php
public function favoriteMaterials(){
    return $this->favorites()->where("favoriteable_type", "=", \App\Material::class);
}
```

then load that instead:

```php
$user->load("favoriteMaterials");

// or when building the query
$users = \App\User::with("favoriteMaterials");

```
