### ISSUE TITLE
How to display the count of Likes a user has received?

### ISSUE THREAD

**Issue by Snakzi** [ChristianKuri/laravel-favorite#18]
Please help me :)

**Comment by ChristianKuri** [comment]
$post->favoritesCount; // returns the number of users that have marked as favorite this object.

**Comment by Snakzi** [comment]
I'm not talking about the post, I'm talking about the amount of likes a user has received with ALL his posts.

**Comment by ChristianKuri** [comment]
You could write a query to fetch all the users post with favorites and then count
