### ISSUE TITLE
Custom Model

### ISSUE THREAD

**Issue by danpalmieri** [ChristianKuri/laravel-favorite#19]
Any chance of creating a custom Favorite model and extending the original?

Thanks!

**Comment by ChristianKuri** [comment]
You could extend it and modify the migration, which is exportable. If you find a better solution you could open a pull request.

**Comment by ChristianKuri** [comment]
I forgot to say that the traits would not allow you to do that. The solution is to add a config file which accepts the Favorite model, so in case that the favorite model is changed you just need to change the config file. I dont have the time to make the changes right now. If you want feel free to open a pull request. If not ill do it later.

**Comment by mdbtekny** [comment]
Hi @ChristianKuri , how can I do it?
